# Configure JDBC datasource OR JNDI datasource
# EVAPRO Datasource configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres_db
spring.datasource.username=postgres_user
spring.datasource.password=postgres_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# EVAPRO JNDI configuration
#spring.datasource.jndi-name =  java:/comp/env/jdbc/|eva.evapro.datasource|

#Avoid hibernate ddl schema generation/update or validation
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jmx.enabled = false

springfox.documentation.swagger.v2.path=/webservices/api

#spring.profiles.active=oauth2-security
#security.oauth2.resource.user-info-uri = ...

spring.data.mongodb.host=mongodb:27017
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=mongo_user
spring.data.mongodb.password=mongo_pass
spring.data.mongodb.read-preference=primaryPreferred

db.collection-names.files=files_2_0
db.collection-names.variants=variants_2_0
db.collection-names.annotation-metadata=annotationMetadata_2_0
db.collection-names.features=features_2_0
db.collection-names.annotations=annotations_2_0

contig-alias.url=https://localhost:8080/contig-alias

management.endpoints.web.exposure.include=info,health
management.info.git.mode=simple

# Spring Boot 2 MongoDB driver needs an authentication mechanism
spring.data.mongodb.authentication-mechanism=SCRAM-SHA-1
# See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
spring.main.allow-bean-definition-overriding=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

management.metrics.binders.jvm.enabled=false

server.servlet.context-path=/eva