stages:
    - build
    - deploy

# Shared .build_docker / .update_and_deploy templates live in eva-k8s
# See https://github.com/EBIvariation/eva-k8s/blob/main/gitlab-ci/webservice.yml.
include:
    - remote: 'https://raw.githubusercontent.com/EBIvariation/eva-k8s/refs/tags/v1.0/gitlab-ci/webservice.yml'

# REQUIRED GitLab CI/CD Variables (Global):
# DOCKER_AUTH_CONFIG: Contains username and password for the docker registry above
# GITHUB_USER: GitHub username for accessing private maven settings repository
# GITHUB_TOKEN: GitHub personal access token for accessing private maven settings repository

variables:
    IMAGE_REPOSITORY: dockerhub.ebi.ac.uk/ebivariation/eva-ws

# ============================================================================
# eva-server
# ============================================================================

build:docker:eva-server:dev:
    extends: .build_docker
    variables:
        SERVICE_NAME: eva-server
        DOCKERFILE_PATH: eva-server/Dockerfile
        IMAGE_TAG: eva-server-dev-$CI_COMMIT_SHORT_SHA
    only:
        - master

deploy:eva-server:dev:
    extends: .update_and_deploy
    needs:
        - build:docker:eva-server:dev
    variables:
        SERVICE_NAME: eva-server
        IMAGE_TAG: eva-server-dev-$CI_COMMIT_SHORT_SHA
        ENV: development
        MAVEN_PROFILE: development
        K8S_MANIFEST_PATH: k8s-manifests/eva-server/overlays/dev
        K8S_NAMESPACE: eva-server-dev
        KUBECONFIG_FILE: $KUBECONFIG_FILE_DEV
    environment:
        name: development
    only:
        - master

deploy:eva-server:staging:
    extends: .update_and_deploy
    needs:
        - build:docker:eva-server:dev
    variables:
        SERVICE_NAME: eva-server
        IMAGE_TAG: eva-server-dev-$CI_COMMIT_SHORT_SHA
        ENV: staging
        MAVEN_PROFILE: production_processing
        K8S_MANIFEST_PATH: k8s-manifests/eva-server/overlays/staging
        K8S_NAMESPACE: eva-server-stage
        KUBECONFIG_FILE: $KUBECONFIG_FILE_STAGING
    environment:
        name: staging
    only:
        - master

build:docker:eva-server:prod:
    extends: .build_docker
    variables:
        SERVICE_NAME: eva-server
        DOCKERFILE_PATH: eva-server/Dockerfile
        IMAGE_TAG: eva-server-$CI_COMMIT_TAG
    only:
        - tags

deploy:eva-server:prod:
    extends: .update_and_deploy
    needs:
        - build:docker:eva-server:prod
    variables:
        SERVICE_NAME: eva-server
        IMAGE_TAG: eva-server-$CI_COMMIT_TAG
        ENV: prod
        MAVEN_PROFILE: production,$ACTIVE_EVAPRO
        K8S_MANIFEST_PATH: k8s-manifests/eva-server/overlays/prod
        K8S_NAMESPACE: eva-server-prod
        KUBECONFIG_FILE: $KUBECONFIG_FILE_PROD
    environment:
        name: prod
    only:
        - tags

# ============================================================================
# eva-release
# ============================================================================

build:docker:eva-release:dev:
    extends: .build_docker
    variables:
        SERVICE_NAME: eva-release
        DOCKERFILE_PATH: eva-release/Dockerfile
        IMAGE_TAG: eva-release-dev-$CI_COMMIT_SHORT_SHA
    only:
        - master

deploy:eva-release:dev:
    extends: .update_and_deploy
    needs:
        - build:docker:eva-release:dev
    variables:
        SERVICE_NAME: eva-release
        IMAGE_TAG: eva-release-dev-$CI_COMMIT_SHORT_SHA
        ENV: development
        MAVEN_PROFILE: development
        K8S_MANIFEST_PATH: k8s-manifests/eva-release/overlays/dev
        K8S_NAMESPACE: eva-release-dev
        KUBECONFIG_FILE: $KUBECONFIG_FILE_DEV
    environment:
        name: development
    only:
        - master

deploy:eva-release:staging:
    extends: .update_and_deploy
    needs:
        - build:docker:eva-release:dev
    variables:
        SERVICE_NAME: eva-release
        IMAGE_TAG: eva-release-dev-$CI_COMMIT_SHORT_SHA
        ENV: staging
        MAVEN_PROFILE: production_processing
        K8S_MANIFEST_PATH: k8s-manifests/eva-release/overlays/staging
        K8S_NAMESPACE: eva-release-stage
        KUBECONFIG_FILE: $KUBECONFIG_FILE_STAGING
    environment:
        name: staging
    only:
        - master

build:docker:eva-release:prod:
    extends: .build_docker
    variables:
        SERVICE_NAME: eva-release
        DOCKERFILE_PATH: eva-release/Dockerfile
        IMAGE_TAG: eva-release-$CI_COMMIT_TAG
    only:
        - tags

deploy:eva-release:prod:
    extends: .update_and_deploy
    needs:
        - build:docker:eva-release:prod
    variables:
        SERVICE_NAME: eva-release
        IMAGE_TAG: eva-release-$CI_COMMIT_TAG
        ENV: prod
        MAVEN_PROFILE: production,$ACTIVE_EVAPRO
        K8S_MANIFEST_PATH: k8s-manifests/eva-release/overlays/prod
        K8S_NAMESPACE: eva-release-prod
        KUBECONFIG_FILE: $KUBECONFIG_FILE_PROD
    environment:
        name: prod
    only:
        - tags


build:docker:count-stats:dev:
    extends: .build_docker
    variables:
        SERVICE_NAME: count-stats
        DOCKERFILE_PATH: count-stats/Dockerfile
        IMAGE_TAG: count-stats-dev-$CI_COMMIT_SHORT_SHA
    only:
        - master

deploy:count-stats:dev:
    extends: .update_and_deploy
    needs:
        - build:docker:count-stats:dev
    variables:
        SERVICE_NAME: count-stats
        IMAGE_TAG: count-stats-dev-$CI_COMMIT_SHORT_SHA
        ENV: development
        MAVEN_PROFILE: development
        K8S_MANIFEST_PATH: k8s-manifests/count-stats/overlays/dev
        K8S_NAMESPACE: count-stats-dev
        KUBECONFIG_FILE: $KUBECONFIG_FILE_DEV
    environment:
        name: development
    only:
        - master

deploy:count-stats:staging:
    extends: .update_and_deploy
    needs:
        - build:docker:count-stats:dev
    variables:
        SERVICE_NAME: count-stats
        IMAGE_TAG: count-stats-dev-$CI_COMMIT_SHORT_SHA
        ENV: staging
        MAVEN_PROFILE: production_processing
        K8S_MANIFEST_PATH: k8s-manifests/count-stats/overlays/staging
        K8S_NAMESPACE: count-stats-stage
        KUBECONFIG_FILE: $KUBECONFIG_FILE_STAGING
    environment:
        name: staging
    only:
        - master

build:docker:count-stats:prod:
    extends: .build_docker
    variables:
        SERVICE_NAME: count-stats
        DOCKERFILE_PATH: count-stats/Dockerfile
        IMAGE_TAG: count-stats-$CI_COMMIT_TAG
    only:
        - tags

deploy:count-stats:prod:
    extends: .update_and_deploy
    needs:
        - build:docker:count-stats:prod
    variables:
        SERVICE_NAME: count-stats
        IMAGE_TAG: count-stats-$CI_COMMIT_TAG
        ENV: prod
        MAVEN_PROFILE: production,$ACTIVE_EVAPRO
        K8S_MANIFEST_PATH: k8s-manifests/count-stats/overlays/prod
        K8S_NAMESPACE: count-stats-prod
        KUBECONFIG_FILE: $KUBECONFIG_FILE_PROD
    environment:
        name: prod
    only:
        - tags

# ============================================================================
# dgva-server
# ============================================================================
# NOTE: Bo dev *deploy* job for dgva-server because there are no DGVA dev database to connect to

build:docker:dgva-server:dev:
    extends: .build_docker
    variables:
        SERVICE_NAME: dgva-server
        DOCKERFILE_PATH: dgva-server/Dockerfile
        IMAGE_TAG: dgva-server-dev-$CI_COMMIT_SHORT_SHA
    only:
        - master

deploy:dgva-server:staging:
    extends: .update_and_deploy
    needs:
        - build:docker:dgva-server:dev
    variables:
        SERVICE_NAME: dgva-server
        IMAGE_TAG: dgva-server-dev-$CI_COMMIT_SHORT_SHA
        ENV: staging
        MAVEN_PROFILE: production_processing
        K8S_MANIFEST_PATH: k8s-manifests/dgva-server/overlays/staging
        K8S_NAMESPACE: dgva-server-stage
        KUBECONFIG_FILE: $KUBECONFIG_FILE_STAGING
    environment:
        name: staging
    only:
        - master

build:docker:dgva-server:prod:
    extends: .build_docker
    variables:
        SERVICE_NAME: dgva-server
        DOCKERFILE_PATH: dgva-server/Dockerfile
        IMAGE_TAG: dgva-server-$CI_COMMIT_TAG
    only:
        - tags

deploy:dgva-server:prod:
    extends: .update_and_deploy
    needs:
        - build:docker:dgva-server:prod
    variables:
        SERVICE_NAME: dgva-server
        IMAGE_TAG: dgva-server-$CI_COMMIT_TAG
        ENV: prod
        MAVEN_PROFILE: production,$ACTIVE_EVAPRO
        K8S_MANIFEST_PATH: k8s-manifests/dgva-server/overlays/prod
        K8S_NAMESPACE: dgva-server-prod
        KUBECONFIG_FILE: $KUBECONFIG_FILE_PROD
    environment:
        name: prod
    only:
        - tags
