# Configure JDBC datasource OR JNDI datasource
# DGVAPRO Datasource configuration
#spring.datasource.url=|dgvapro.host|
#spring.datasource.username=|dgvapro.user|
#spring.datasource.password=|dgvapro.passwd|
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.jdbc.pool.OracleDataSource

# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto = none

spring.jmx.enabled = false

springfox.documentation.swagger.v2.path=/webservices/api

management.endpoints.web.exposure.include=info,health
management.info.git.mode=simple

# See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
spring.main.allow-bean-definition-overriding=true

management.metrics.binders.jvm.enabled=false

server.servlet.context-path=/dgva