spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=|eva.evapro.jdbc.url|
#spring.datasource.username=|eva.evapro.user|
#spring.datasource.password=|eva.evapro.password|
#spring.jpa.hibernate.ddl-auto=update
#controller.auth.admin.username=|eva.count-stats.username|
#controller.auth.admin.password=|eva.count-stats.password|

# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

management.metrics.binders.jvm.enabled=false

server.servlet.context-path=/eva/webservices/count-stats

management.endpoints.web.exposure.include=info,health
management.info.git.mode=simple