spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres_db
spring.datasource.username=postgres_user
spring.datasource.password=postgres_pass
spring.jpa.hibernate.ddl-auto=update
controller.auth.admin.username=count-stats-admin-user
controller.auth.admin.password=count-stats-admin-pass

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

management.metrics.binders.jvm.enabled=false

server.servlet.context-path=/eva/webservices/count-stats

management.endpoints.web.exposure.include=info,health
management.info.git.mode=simple